# This is a basic workflow to help you get started with Actions

name: OpenWrt-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the openwrt-18.06 branch
on:
  push:
    branches: [ openwrt-18.06 ]
  pull_request:
    branches: [ openwrt-18.06 ]
  schedule:
    - cron: 0 22 */2 * * 
  watch:
    types: started
    
jobs:

  build_openwrt:

    name: OpenWrt_Build 

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev curl patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "Asia/Shanghai"
      - name: Update feeds
        run: |
          sudo chown -R runner:runner /home/runner/work/openwrt
          rm -rf ./package/lean/luci-theme-argon
          rm -rf ./package/lean/trojan
          rm -rf ./package/lean/luci-lib-docker
          rm -rf ./package/lean/luci-theme-opentomcat
          rm -rf ./package/lean/luci-app-netdata
          sed -i '$a src-git  helloworld https://github.com/fw876/helloworld' ./feeds.conf.default
          sed -i '$a src-git diy https://github.com/siropboy/mypackages' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Update package
        run: |
          rm -rf ./feeds/packages/admin/netdata
          sed -i 's/= "unreachable"/= "default"/g' feeds/luci/applications/luci-app-mwan3/luasrc/model/cbi/mwan/policyconfig.lua
          sed -i 's/带宽监控/监控/g' feeds/luci/applications/luci-app-nlbwmon/po/zh-cn/nlbwmon.po
          curl -fsSL  https://raw.githubusercontent.com/siropboy/other/master/patch/poweroff/poweroff.htm > ./feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_system/poweroff.htm 
          curl -fsSL  https://raw.githubusercontent.com/siropboy/other/master/patch/poweroff/system.lua > ./feeds/luci/modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
          curl -fsSL  https://raw.githubusercontent.com/siropboy/other/master/patch/default-settings/zzz-default-settings > ./package/lean/default-settings/files/zzz-default-settings
          sed -i 's/实时流量监测/监测/g' package/lean/luci-app-wrtbwmon/po/zh-cn/wrtbwmon.po
          sed -i 's/网络存储/存储/g' package/lean/luci-app-vsftpd/po/zh-cn/vsftpd.po
          #sed -i 's/Turbo ACC 网络加速/ACC网络加速/g' package/lean/luci-app-flowoffload/po/zh-cn/flowoffload.po
          sed -i 's/Turbo ACC 网络加速/ACC网络加速/g' package/lean/luci-app-sfe/po/zh-cn/sfe.po
          sed -i 's/解锁网易云灰色歌曲/解锁灰色歌曲/g' package/lean/luci-app-unblockmusic/po/zh-cn/unblockmusic.po
          sed -i 's/家庭云//g' package/lean/luci-app-familycloud/luasrc/controller/familycloud.lua
          sed -i '/filter_aaaa/d' package/network/services/dnsmasq/files/dhcp.conf
          sed -i 's/$(VERSION_DIST_SANITIZED)/$(shell date +%Y%m%d)-$(VERSION_DIST_SANITIZED)/g' include/image.mk
          curl -fsSL https://raw.githubusercontent.com/siropboy/other/master/patch/autocore/files/index.htm > package/lean/autocore/files/index.htm
          echo "DISTRIB_REVISION='S$(date +%Y.%m.%d) Sirpdboy'" > ./package/base-files/files/etc/openwrt_release1
          svn co https://github.com/siropboy/other/trunk/patch/netdata feeds/packages/admin/netdata
          git clone https://github.com/NateLol/luci-app-beardropper package/new/luci-app-beardropper
          sed -i 's/"luci.fs"/"luci.sys".net/g' package/new/luci-app-beardropper/luasrc/model/cbi/beardropper/setting.lua
          sed -i '/firewall/d' package/new/luci-app-beardropper/root/etc/uci-defaults/luci-beardropper
          mv package/new/luci-app-beardropper/po/zh_Hans   package/new/luci-app-beardropper/po/zh-cn
          git clone -b master --single-branch https://github.com/tty228/luci-app-serverchan package/new/luci-app-serverchan
          svn co https://github.com/kenzok8/openwrt-packages/trunk/luci-app-smartdns package/new/luci-app-smartdns
          svn co https://github.com/firker/diy-ziyong/trunk/smartdns package/smartdns
          git clone -b master --single-branch https://github.com/destan19/OpenAppFilter package/new/OpenAppFilter
          svn co https://github.com/kenzok8/openwrt-packages/trunk/adguardhome package/new/AdGuardHome
          svn co https://github.com/kenzok8/openwrt-packages/trunk/luci-app-adguardhome package/new/luci-app-adguardhome
          git clone -b master --single-branch https://github.com/vernesong/OpenClash package/new/openclash
          git clone -b master --single-branch https://github.com/frainzy1477/luci-app-clash package/new/luci-app-clash
          sed -i 's/), 5)/), 48)/g' package/new/luci-app-clash/luasrc/controller/clash.lua
          sed -i 's/), 1)/), 48)/g' package/new/luci-app-clash/luasrc/controller/clash.lua
          svn co https://github.com/jerrykuku/luci-app-vssr/trunk/  package/new/luci-app-vssr
          svn co https://github.com/jerrykuku/luci-app-jd-dailybonus/trunk/ package/new/luci-app-jd-dailybonus
          git clone  https://github.com/lisaac/luci-lib-docker.git package/new/luci-lib-docker
          git clone  https://github.com/lisaac/luci-app-dockerman.git package/new/luci-app-dockerman
          svn co https://github.com/xiaorouji/openwrt-package/trunk/lienol/luci-app-passwall package/new/luci-app-passwall
          svn co https://github.com/xiaorouji/openwrt-package/trunk/package/trojan-go package/new/trojan-go
          svn co https://github.com/xiaorouji/openwrt-package/trunk/package/trojan-plus package/new/trojan-plus
          svn co https://github.com/xiaorouji/openwrt-package/trunk/package/trojan package/new/trojan
          svn co https://github.com/xiaorouji/openwrt-package/trunk/package/brook package/brook
          svn co https://github.com/xiaorouji/openwrt-package/trunk/package/chinadns-ng package/chinadns-ng
          svn co https://github.com/xiaorouji/openwrt-package/trunk/package/tcping package/tcping
          
      - name: Generate configuration file
        run: |
          curl -fsSL https://raw.githubusercontent.com/siropboy/other/master/patch/x86-64/allappdrv.config > .config
          make defconfig
      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: Prepare Artifact
        run: |
          mkdir -p ./new/firmware
          mkdir -p ./new/package
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./new/package
          find bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./new/firmware
          cd ./new/firmware
          gzip *.img
      - name: Upload Firmware
        uses: actions/upload-artifact@main
        with:
          name: SirpdboyOpenWrt-IPV6-Firmware
          path: ./new/firmware
      - name: Upload  IPK
        uses: actions/upload-artifact@main
        with:
          name: SirpdboyOpenWrt-IPV6-Ipk
          path: ./new/package
      - name: Upload firmware to cowtransfer
        run: |
         curl -fsSL git.io/file-transfer | sh
         ./transfer cow --block 2621440 -s -p 64 --no-progress ./new/firmware 2>&1 | tee cowtransfer.log
         echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
      - name: Upload Firmware wetransfer
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer wet -s -p 16 --no-progress ./new/firmware 2>&1 | tee wetransfer.log
          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
